name: Build and Sign APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Patch APK
        run: |
          python3 patch_apk.py

      - name: Sign APK Manual
        run: |
          # 1. Localizar ferramentas
          ZIPALIGN=$(find $ANDROID_HOME/build-tools -name zipalign | sort -r | head -n 1)
          APKSIGNER=$(find $ANDROID_HOME/build-tools -name apksigner | sort -r | head -n 1)
          
          # 2. Alinhamento
          $ZIPALIGN -f -v 4 proxyandroid_to_sign.apk proxyandroid_aligned.apk
          
          # 3. Decodificar Keystore
          echo "${{ secrets.SIGNING_KEY }}" | base64 -d > release.jks
          
          # 4. Assinar
          $APKSIGNER sign --ks release.jks \
            --ks-key-alias "${{ secrets.ALIAS }}" \
            --ks-pass pass:"${{ secrets.KEY_STORE_PASSWORD }}" \
            --key-pass pass:"${{ secrets.KEY_PASSWORD }}" \
            --out proxyandroid_signed.apk \
            proxyandroid_aligned.apk
            
          # 5. Verificar
          $APKSIGNER verify proxyandroid_signed.apk

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: proxyandroid-no-login
          path: proxyandroid_signed.apk
